spring:
  application:
    name: admin-service
  profiles:
    active: local
  threads:
    virtual:
      # 启用虚拟线程
      enabled: true
  config:
    import:
      - classpath:config/${spring.profiles.active}/flyway.yml
      - classpath:config/${spring.profiles.active}/knife4j.yml
      - classpath:config/${spring.profiles.active}/minio.yml
      - classpath:config/${spring.profiles.active}/mybatis-flex.yml
      - classpath:config/${spring.profiles.active}/mysql.yml
      - classpath:config/${spring.profiles.active}/page-helper.yml
      - classpath:config/${spring.profiles.active}/redis.yml
      - classpath:config/${spring.profiles.active}/sa-token.yml

  mvc:
    path-match:
      matching-strategy: ant_path_matcher

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
# 生成工具
generator:
  path:
    # 前端项目地址
    web:
    # 后端项目地址，默认自动检测springboot项目路径，无需配置。
    api: E://code//Gitlab//sz-framework//sz-admin
  # 模块名，指定代码生成的模块
  module-name: sz-service
  service-name: sz-service-admin
  global:
    author: sz-admin
    packages: com.sz.admin
# 微信生态
wechat:
  # 小程序
  mini:
    app-id: your_app_id
    app-secret: your_app_secret
app:
  version: @project.version@
# 是否启用数据权限拼接
data-scope:
  enable: true
  # 数据逻辑实现最小验证（查询）单位：dept 部门（dept_scope字段）、user 用户 (create_id 字段),默认user。
  logic-min-unit: user

